name: SSHX Runner

on:
  workflow_dispatch:   # manually trigger

jobs:
  sshx:
    runs-on: depot-macos-15	
    steps:
      - name: Run SSHX
        run: curl -sSf https://sshx.io/get | sh -s run
        if: always()
